version: '3'

tasks:
  docker_network:
    desc: "Create docker network for project."
    aliases:
      - network
    cmd: sudo docker network create hmtm_network

  prod:
    desc: "Run application and it's dependencies for production."
    cmds:
      - task: create_logs_folder
      - task: prepare_env_file_prod
      - task: docker_build_prod
      - task: docker_run_prod

  create_logs_folder:
    desc: "Create logs folder for docker volume purposes."
    internal: true
    dir: ../
    cmds:
      - mkdir -p logs

  prepare_env_file_prod:
    desc: "Prepare .env file for production."
    internal: true
    dir: ../
    cmds:
      - cp .env.prod ./deploy/prod/.env

  docker_build_prod:
    desc: "Build docker container for production."
    aliases:
      - build_prod
    cmd: sudo docker compose -f ../deploy/prod/docker-compose.yml build

  docker_run_prod:
    desc: "Launch docker container for production."
    aliases:
      - run_prod
    cmd: sudo docker compose -f ../deploy/prod/docker-compose.yml up

  docker_stop:
    desc: "Stop all docker containers."
    aliases:
      - stop
    cmd: sudo docker stop $(sudo docker ps -a -q)

  docker_clean:
    desc: "Clean docker containers, images and volumes."
    cmd: sudo docker system prune -a --volumes

  clean_up:
    desc: "Clean up all folders, docker volumes, images and containers."
    dir: ../
    aliases:
      - clean
    cmds:
      - sudo rm -rf logs/
      - sudo rm -rf coverage/
      - sudo rm -rf deploy/prod/.env
      - task: docker_clean

  upload_docker_image:
    desc: "Uploads docker image to dockerhub."
    aliases:
      - upload
    dir: ../
    cmds:
      - task: prepare_env_file_prod
      - task: docker_build_prod
      - sudo docker tag hmtm_bdu d3m0s/hmtm_bdu
      - sudo docker push d3m0s/hmtm_bdu
